/** Category emoji for dashboard lists. Names follow the live 35-class taxonomy. */
export const CATEGORY_EMOJI: Record<string, string> = {
  餐饮美食: "🍽️",
  交通出行: "🚗",
  商超购物: "🛒",
  日用百货: "🧺",
  房屋租金: "🏠",
  物业费用: "🏠",
  水电燃气: "🏠",
  通讯话费: "📱",
  宽带网络: "📡",
  医疗诊疗: "🏥",
  药品保健: "💊",
  教育学习: "👶",
  书籍文具: "📚",
  休闲娱乐: "🎮",
  影视演出: "🎬",
  运动健身: "🏃",
  旅游度假: "✈️",
  酒店住宿: "🏨",
  人情送礼: "🎁",
  红包礼金: "🧧",
  宠物养护: "🐾",
  服饰鞋包: "👗",
  美容个护: "✨",
  数码产品: "💻",
  家居家装: "🏠",
  保险缴费: "🛡️",
  还贷支出: "🏦",
  税费支出: "🧾",
  工资收入: "💰",
  副业收入: "💼",
  购物退款: "↩️",
  票务退款: "🎫",
  报销到账: "📑",
  优惠返现: "💵",
  他人还款: "🤝",
};

export const categoryEmoji = (category: string) => CATEGORY_EMOJI[category] ?? "📌";
